Dragon api
amrendrakind/space-travelers pull request #188
Opened 2022-05-17 10:02 UTC by Ol-create

Fetch data from the Dragons endpoint  (https://api.spacexdata.com/v3/dragons) when a user navigates to the Dragons section.

Once the data are fetched, dispatch an action to store the selected data in Redux store:

- id
- name
- type
- flickr_images

- Follow the same logic as with the "Reserve dragon" - but you need to set the `reserved` key to `false`. 
- Dispatch these actions upon click on the corresponding buttons.

NOTE: Make sure you only dispatch those actions once and do not add data to store on every re-render (i.e. when changing views / using navigation).

2022-05-18 17:37 UTC, amrendrakind requested changes
Hi @Ol-create    :wave: :wave: 

![almost-there](https://user-images.githubusercontent.com/75126481/160092588-b3f37e8e-a1d9-4b14-84fc-7ec1fed7b3e5.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Your PR has a proper title and description  :+1: 
- Your linters are passing :heavy_check_mark:  
- Profesional README file :rocket: 

## Required Changes ♻️

_Check the comments under the review._

Cheers and Happy coding!👏👏👏

2022-05-18 17:37 UTC, amrendrakind commented on src/redux/configureStore.js
> +  // missions,
- [ ] Please remove commented code as it is not a good practice from a clean code context. :wink:

2022-05-18 17:37 UTC, amrendrakind commented on src/redux/dragons/dragon.js
> +const UNRESERVEDRAGON = 'UNRESERVEDRAGON';
- [ ] [OPTIONAL]  Consider using :duck:  duck pattern as recommended :smile:

2022-05-19 20:55 UTC, Ol-create commented
hi @amrendrakind thank you for your effort.
The comment has been resolved

2022-05-19 20:58 UTC, amrendrakind approved these changes
### Status: Approved :100: 

Hi @Ol-create 👋🏾,

![image](https://user-images.githubusercontent.com/78268827/169403409-d798171d-bfeb-4830-a8a5-6090e5b1e813.png)

Your project is complete! 👏🏾
There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! tada tada

Top Highlights 💪🏻
:heavy_check_mark: Good use of Pull Request
:heavy_check_mark: No linter errors.
:heavy_check_mark: You used the correct Git-flow.
:heavy_check_mark: Commit messages are meaningful.
:heavy_check_mark: The app works as expected
:heavy_check_mark: Good quality of code

Cheers and Happy coding! :clap: :clap: :clap: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @amrendrakind in your question so I can receive the notification.

2022-05-19 21:01 UTC, merged